import type { WikiBudget, WikiStatus } from "./types";
import { today } from "./workspace";

export const agentsSection = `<!-- PROJECT-WIKI-FIRST:START -->
## Wiki-First Planning

This project uses \`./wiki\` as the durable project-planning source of truth.

At the start of every session:

1. Review \`wiki/startup.md\` for compact current context.
2. Review \`wiki/index.md\` as the router for which files to read next.
3. Read detailed \`wiki/canonical/\`, \`wiki/decisions/\`, \`wiki/meta/\`, and \`wiki/sources/\` files on demand only when the current question needs them.

During conversation:

- Update \`./wiki\` in the same turn when project planning content is added, changed, or removed.
- Do not store non-project LLM memory, assistant preferences, collaboration reminders, or workflow instructions in project wiki canonical or decision docs.
- Follow \`wiki/AGENTS.md\` for detailed rules when editing files under \`wiki/\`.
- Let \`.githooks/prepare-commit-msg\` append wiki trailers automatically for staged wiki, hook, AGENTS, or project-librarian files.
<!-- PROJECT-WIKI-FIRST:END -->`;

export const claudeSection = `<!-- PROJECT-WIKI-CLAUDE:START -->
# Claude Code Project Instructions

@AGENTS.md

## Claude Code Notes

Claude Code reads \`CLAUDE.md\`, not \`AGENTS.md\`, so this file imports \`AGENTS.md\` to share the same wiki-first planning contract with Codex and other agents. Bootstrap also installs a Claude Code \`SessionStart\` hook in \`.claude/settings.json\` for compact wiki startup context.

At session start, follow the imported instructions: review \`wiki/startup.md\` and \`wiki/index.md\` first, then read detailed wiki pages on demand only when the current task needs them.
<!-- PROJECT-WIKI-CLAUDE:END -->`;

export const geminiSection = `<!-- PROJECT-WIKI-GEMINI:START -->
# Gemini CLI Project Instructions

@AGENTS.md

## Gemini CLI Notes

Gemini CLI reads \`GEMINI.md\` by default, so this file imports \`AGENTS.md\` to share the same wiki-first planning contract with Codex, Claude Code, Cursor, and other agents.

At session start, follow the imported instructions: review \`wiki/startup.md\` and \`wiki/index.md\` first, then read detailed wiki pages on demand only when the current task needs them.
<!-- PROJECT-WIKI-GEMINI:END -->`;

export const cursorRule = `---
alwaysApply: true
---

# Project Librarian Wiki-First Planning

Use the repository root \`AGENTS.md\` as the project-wide instruction source.

@AGENTS.md
`;

export const wikiAgentsSection = `<!-- PROJECT-WIKI-INTERNAL:START -->
## Wiki Internal Rules

This file applies to \`./wiki\` and its children. Root \`AGENTS.md\` owns the project-wide wiki-first contract. Root \`CLAUDE.md\` and \`GEMINI.md\` import \`AGENTS.md\` for agent compatibility. This file owns detailed wiki editing rules.

Language policy:

- Wiki operating documents generated by this bootstrap are English by default.
- Project canonical content does not have a fixed default language. The LLM should choose the language that best matches the user's language, project context, and surrounding materials, then keep that choice consistent.
- If the user explicitly asks for a language, that instruction wins.

Reading rules:

- Treat \`startup.md\` as compact session context and \`index.md\` as the router.
- Read detailed \`canonical/\`, \`decisions/\`, \`meta/\`, and \`sources/\` files on demand only when the current question needs them.
- Prefer each file's TL;DR and metadata before reading the full body.

Storage boundaries:

- \`canonical/\` contains current project-planning truth only.
- \`decisions/\` contains project decision history only.
- \`meta/\` contains wiki operating rules, decision policy, bootstrap, lint, hook, and migration decisions.
- \`sources/\` contains external reference summaries and source notes.
- \`inbox/\` and migration inbox files contain candidates, not canonical truth.
- Do not store non-project LLM memory, assistant preferences, collaboration reminders, or workflow instructions in \`canonical/\` or \`decisions/\`; use root \`AGENTS.md\`, compatibility instruction files, hooks, rules, or skills instead.
- During migration review, do not copy legacy markdown files directly into \`canonical/\`, \`decisions/\`, or \`sources/\`. Rewrite only the useful project meaning, cite current-project evidence when possible, and keep unresolved or ambiguous material in migration inboxes.

Update rules:

- Every wiki knowledge markdown file should include compact metadata with \`status\`, \`updated\`, \`scope\`, \`read_budget\`, \`decision_ref\`, and \`review_trigger\`. This \`wiki/AGENTS.md\` instruction file is excluded from that wiki-page metadata requirement.
- Put a compact TL;DR near the top of canonical, decision, meta, source, inbox, and migration pages.
- Update \`startup.md\` when session-start summary, recent important decisions, open questions, routing hints, or project-language choice changes.
- Update \`index.md\` when adding, moving, removing, or materially changing wiki pages.
- Use \`decisions/log.md\` for trivial timestamped project decisions, Decision Packs for grouped topic decisions, and Full ADRs only for product direction, architecture, public API, data model, security/permission, SEO contract, high migration-cost, or likely-to-be-challenged decisions.
- Initialize \`canonical/glossary.md\` only when terminology becomes useful.
- Keep migration inbox statuses as \`pending\`, \`adopted\`, \`rejected\`, \`resolved\`, or \`needs-human-review\`.

Commit rules:

- Follow the repository's commit-message policy when one exists.
- Let \`.githooks/prepare-commit-msg\` append wiki trailers automatically when git hooks are enabled.
- If bootstrap was run with \`--no-git-config\`, hook files are installed but \`core.hooksPath\` is not changed.
- Do not hand-write wiki trailers unless the hook is unavailable or a trailer needs correction.
<!-- PROJECT-WIKI-INTERNAL:END -->`;

export const metadata = (scope: string, budget: WikiBudget, decisionRef: string, trigger: string, status: WikiStatus = "active"): string => `---
status: ${status}
updated: ${today}
scope: ${scope}
read_budget: ${budget}
decision_ref: ${decisionRef}
review_trigger: ${trigger}
---
`;

export const startup = `${metadata("startup-router", "short", "wiki/meta/wiki-ops-v1-decisions.md", "session-start summary, routing, language policy, or open project state changes")}
# Startup Context

## TL;DR

- This project is in an initial planning state unless the canonical wiki says otherwise.
- Project truth lives in \`wiki/canonical/\`, project decision history lives in \`wiki/decisions/\`, and source summaries live in \`wiki/sources/\`.
- Wiki operating rules and wiki operating decisions live in \`wiki/meta/\`.
- At session start, read only this file and \`wiki/index.md\` first; read detailed files on demand.
- Project canonical content language is not fixed by this bootstrap. The LLM should choose the language that best matches the user and project context.
- Update the wiki in the same turn when project-planning content changes.

## Read On Demand

- [[index]]: document router.
- [[canonical/project-brief]]: read only when product direction, audience, scope, success criteria, or core scenarios matter.
- [[canonical/open-questions]]: read only when unresolved questions or next clarification items matter.
- [[canonical/assumptions]]: read only when temporary assumptions or unverified premises matter.
- [[canonical/risks]]: read only when risks, revisit triggers, or uncertainty matter.

## Project State

- Problem/opportunity: not selected yet.
- Target users: not selected yet.
- Core scenario: not selected yet.
- Success criteria: not selected yet.
- Initial scope: not selected yet.
- Project content language: to be selected from user/project context.

## Recent Project Decisions

- None yet.

## Wiki Operating Pointers

- Decision recording follows [[meta/decision-policy]].
- Wiki operation follows [[meta/operating-model]].
- Wiki operating decisions are recorded only in [[meta/wiki-ops-v1-decisions]], not in project decision logs.

## Token Discipline

- Codex, Claude Code, and Cursor session-start hooks inject only this file and \`wiki/index.md\`; Gemini uses generated context instructions that route agents to the same compact context.
- Detailed files are selected by the "read when" rules in \`wiki/index.md\`.
- Long decision history is not injected wholesale; read only relevant Decision Packs or ADRs.
`;

export const index = `${metadata("wiki-router", "short", "wiki/meta/wiki-ops-v1-decisions.md", "wiki page added, moved, removed, or routing changes")}
# Wiki Index

## How To Use This Index

This file is a router, not a file to expand into every answer. Read only the files that are relevant to the current question.

## Language Policy

- Operating documents generated by this bootstrap are English by default.
- Project canonical content language is chosen by the LLM from the user's language, project context, and surrounding materials.
- Keep the chosen project language consistent unless the user asks to switch.

## Boundary Rule

- \`wiki/canonical/\` and \`wiki/decisions/\` contain project-planning content only.
- Wiki operating rules and wiki operating decisions live in \`wiki/meta/\`.
- Non-project LLM memory, collaboration reminders, and workflow instructions belong in \`AGENTS.md\`, \`wiki/AGENTS.md\`, hooks, or skills, not in project canonical/decision docs.

## Startup

- [[startup]]
  - Read: every session start or compact project state lookup.
  - Update: startup summary, recent decisions, open questions, routes, language policy.
  - Token budget: short.

## Canonical

- [[canonical/project-brief]]
  - Read: product direction, audience, scope, success criteria, core scenarios.
  - Update: product, audience, scope, or success criteria changes.
  - Token budget: medium.
- [[canonical/open-questions]]
  - Read: unresolved questions or next clarifications.
  - Update: questions are added, answered, or moved.
  - Token budget: short.
- [[canonical/assumptions]]
  - Read: temporary assumptions or unverified premises.
  - Update: assumptions are added, validated, or retired.
  - Token budget: short.
- [[canonical/risks]]
  - Read: risks, revisit triggers, uncertainty.
  - Update: risks are added, mitigated, or resolved.
  - Token budget: short.

## Project Decisions

- [[decisions/recent]]
  - Read: recent important project decisions.
  - Update: a decision belongs in startup context.
  - Token budget: short.
- [[decisions/log]]
  - Read: project decision timing matters.
  - Update: a trivial decision needs timestamp tracking.
  - Token budget: on-demand.
- [[decisions/decision-pack-template]]
  - Read: creating a Decision Pack.
  - Update: Decision Pack format changes.
  - Token budget: short.
- [[decisions/full-adr-template]]
  - Read: creating a Full ADR.
  - Update: Full ADR format changes.
  - Token budget: short.

## Wiki Meta

- [[meta/operating-model]]
  - Read: wiki operation, hooks, bootstrap, maintenance, language policy.
  - Update: wiki operation or startup behavior changes.
  - Token budget: medium.
- [[meta/decision-policy]]
  - Read: decision level, ADR need, canonical/decision split.
  - Update: decision classification or ADR criteria changes.
  - Token budget: medium.
- [[meta/wiki-ops-v1-decisions]]
  - Read: wiki operating decisions, rejected alternatives, rationale.
  - Update when: wiki operating decisions change.
  - Token budget: medium.

## Sources

- [[sources/karpathy-llm-wiki]]
  - Read: source pattern and LLM Wiki rationale.
  - Update: source links, interpretation, application notes.
  - Token budget: short.
`;

export const glossary = `${metadata("project-canonical", "medium", "wiki/meta/wiki-ops-v1-decisions.md", "project terms, roles, states, permissions, events, entities, API names, DB names, or UI labels are added or renamed")}
# Glossary

## TL;DR

- This file is the naming contract for project/product terminology.
- Do not store wiki operating terms, LLM collaboration instructions, or general working memory here.
- Prefer canonical terms from this file for API, database, UI, and policy wording.
- Use the project language chosen in [[startup]] unless the user says otherwise.

## Terms

| Term | Definition | Avoid | Related Canonical Doc | Status |
| --- | --- | --- | --- | --- |
|  |  |  |  | proposed |
`;

export const glossaryIndexBlock = `<!-- PROJECT-WIKI-GLOSSARY:START -->
## Glossary

- [[canonical/glossary]]
  - Read: terms, roles, states, permissions, events, API/DB/UI names, naming conflicts.
  - Update: core term is added, renamed, or deprecated.
  - Token budget: medium.
<!-- PROJECT-WIKI-GLOSSARY:END -->`;

export const inboxIndexBlock = `<!-- PROJECT-WIKI-INBOX:START -->
## Inbox

- [[inbox/project-candidates]]
  - Read: captured project candidates not yet adopted.
  - Update: \`--capture-inbox\` adds a candidate or status changes.
  - Token budget: on-demand.
<!-- PROJECT-WIKI-INBOX:END -->`;

export const wikiOperatingModel = `${metadata("wiki-meta", "medium", "wiki/meta/wiki-ops-v1-decisions.md", "wiki operating rules, hook behavior, bootstrap behavior, language policy, or token policy changes")}
# Wiki Operating Model

## TL;DR

- This wiki keeps project-planning knowledge as durable markdown.
- Codex, Claude Code, and Cursor session-start hooks inject only \`wiki/startup.md\` and \`wiki/index.md\`; Gemini uses generated context instructions that route agents to the same compact context.
- Detailed canonical and decision files are read on demand.
- Root \`AGENTS.md\` keeps the project-wide wiki-first contract; \`wiki/AGENTS.md\` keeps detailed wiki editing rules.
- Operating documents generated by bootstrap are English by default.
- Project canonical content language is selected from user/project context, not hardcoded by this bootstrap.
- Search, index refresh, inbox capture, and lifecycle checks are explicit script modes.

## Purpose

This wiki prevents project-planning knowledge from being trapped in one-off conversations. It gives humans and LLM agents a compact startup path plus durable source-of-truth documents.

## Applied Source Pattern

Karpathy's LLM Wiki pattern favors a continuously maintained markdown wiki over repeatedly rebuilding answers from scratch. This project applies that pattern to project planning.

## Layers

1. Sources: external docs, links, user notes, and evidence summaries.
2. Canonical project truth: current valid planning content under \`wiki/canonical/\`.
3. Project decisions: rationale, rejected alternatives, and revisit triggers under \`wiki/decisions/\`.
4. Startup context: compact session summary in \`wiki/startup.md\`.
5. Router: read/update/token-budget guidance in \`wiki/index.md\`.
6. Wiki meta: operating rules, decision policy, bootstrap, migration, lint, and language policy under \`wiki/meta/\`.

## Language Policy

- Bootstrap-generated operating documents are English.
- Project canonical content should use the language that best matches the user's language, project context, and surrounding materials.
- Keep a consistent project language once selected.
- If the user explicitly requests a language, that request wins.

## Query Procedure

Start with \`wiki/startup.md\` and \`wiki/index.md\`. Then select only relevant canonical, decision, meta, or source files using the "read when" rules.

Use keyword query when explicit search is useful:

\`\`\`bash
node dist/init-project-wiki.js --query "search terms"
\`\`\`

## Token Discipline

- Do not inject long canonical bodies or full decision logs into startup context.
- Put a compact TL;DR near the top of knowledge pages.
- Keep read/update/token-budget hints in \`wiki/index.md\`.
- Use \`decisions/log.md\` for accumulated timestamps and surface only important recent decisions in \`decisions/recent.md\` or \`startup.md\`.

## Git Hook Setup

- The script installs \`.githooks/prepare-commit-msg\` and \`.githooks/wiki-commit-trailers.js\`.
- By default, git repositories with an unset \`core.hooksPath\` are configured with \`git config core.hooksPath .githooks\`.
- Existing \`core.hooksPath\` values are preserved so an existing hook chain is not replaced.
- Run bootstrap with \`--no-git-config\` to install hook files without changing git config.
`;

export const decisionPolicy = `${metadata("wiki-meta", "medium", "wiki/meta/wiki-ops-v1-decisions.md", "project decision recording levels or ADR criteria change")}
# Decision Policy

## TL;DR

- Canonical docs hold current agreement; project decision docs hold rationale and history.
- Simple project changes update canonical docs only.
- Trivial decisions that need timing go into \`decisions/log.md\`.
- Related decisions can be grouped into a Decision Pack.
- Heavy decisions use a Full ADR.
- Wiki operating decisions belong in \`wiki/meta/\`, not project decision history.

## 1. Canonical Only

Use only \`wiki/canonical/\` for simple spec confirmation, current behavior descriptions, reversible wording edits, and low-context changes.

## 2. One-Line Log

Use \`wiki/decisions/log.md\` when the main value is timestamp tracking.

\`\`\`md
- YYYY-MM-DD | area | decision | canonical: [[canonical/example]]
\`\`\`

## 3. Decision Pack

Use a Decision Pack when several related choices share one topic.

| Date | Decision | Rationale | Rejected Alternative | Revisit Trigger | Canonical Link |
| --- | --- | --- | --- | --- | --- |

## 4. Full ADR

Use a Full ADR when the decision affects product direction, architecture, public API, data model, security/permissions, SEO contracts, high migration cost, or a likely future challenge.

## Token Rules

- Put a TL;DR near the top of canonical docs.
- Do not inject full canonical or decision bodies into startup context.
- Read long decision files only when \`wiki/index.md\` routing says they are relevant.
`;

export const starterFiles = {
  "wiki/README.md": `${metadata("wiki-entry", "short", "wiki/meta/wiki-ops-v1-decisions.md", "top-level wiki structure changes")}
# Project Wiki

This directory is the durable project-planning source of truth. Keep product direction, specs, constraints, terms, and decisions current here.

## Start Here

- [[startup]]
- [[index]]
- [[canonical/project-brief]]
- [[canonical/open-questions]]
- [[canonical/assumptions]]
- [[canonical/risks]]
`,
  "wiki/canonical/project-brief.md": `${metadata("project-canonical", "medium", "none", "product direction, audience, scope, success criteria, or language choice changes")}
# Project Brief

## TL;DR

- Current state: product/service topic is not decided yet.
- This file is the current project-planning truth for direction, audience, scope, and success criteria.
- Content language: choose from user/project context and keep it consistent.

## Current State

Product/service topic is not decided yet.

## To Decide

- Problem/opportunity
- Target users
- Core user scenario
- Success criteria
- Key constraints
- Initial scope
`,
  "wiki/canonical/open-questions.md": `${metadata("project-canonical", "short", "none", "project questions are added, answered, or retired")}
# Open Questions

## TL;DR

- This page tracks unresolved project questions.
- Move answered questions into relevant canonical docs or mark them resolved.

## Product

- What problem should this project solve?
- Who is it for?
- What is the first core scenario?
- What counts as success?

## Operations

- None yet.
`,
  "wiki/canonical/assumptions.md": `${metadata("project-canonical", "short", "none", "assumptions are added, validated, or retired")}
# Assumptions

## TL;DR

- This page tracks temporary assumptions before they are validated.
- When an assumption becomes true project knowledge, move it into the relevant canonical doc.

## Active

- Product/service topic is not decided yet.

## Retired

- None.
`,
  "wiki/canonical/risks.md": `${metadata("project-canonical", "short", "none", "project risks are added, mitigated, or resolved")}
# Risks

## TL;DR

- This page tracks project-planning risks and revisit triggers.
- When a risk is resolved, keep the status and evidence.

## Active

| Risk | Impact | Mitigation | Revisit Trigger |
| --- | --- | --- | --- |
| None | - | - | - |

## Resolved

None.
`,
  "wiki/decisions/README.md": `${metadata("project-decisions", "short", "wiki/meta/decision-policy.md", "project decision structure changes")}
# Decisions

## TL;DR

- This directory preserves project decision history.
- Current valid project specs belong in \`../canonical/\`.
- Wiki operating decisions belong in \`../meta/\`.

This directory preserves project decision history. Current valid project specs belong in \`../canonical/\`.

Wiki operation, hook, bootstrap, lint, migration, and language-policy decisions belong in \`../meta/\`, not here.
`,
  "wiki/decisions/log.md": `${metadata("project-decisions", "on-demand", "wiki/meta/decision-policy.md", "trivial project decisions need timestamp tracking")}
# Decision Log

## TL;DR

- This page records lightweight timestamped project decisions when timing matters.
- No project decisions have been logged yet.

No project decisions yet.
`,
  "wiki/decisions/recent.md": `${metadata("project-decisions", "short", "wiki/meta/decision-policy.md", "recent important project decisions change")}
# Recent Decisions

## TL;DR

- Keep only recent important project decisions that may matter at session start.
- Use [[decisions/log]] for full timestamp tracking.

## Decisions

- None yet.
`,
  "wiki/meta/wiki-ops-v1-decisions.md": `${metadata("wiki-meta-decisions", "medium", "self", "wiki operation, metadata, lint, migration, language policy, or storage-boundary decisions change")}
# Wiki Operations v1 Decisions

## TL;DR

- This Decision Pack records accepted wiki operating choices for project-librarian.
- It covers wiki structure, startup hook scope, metadata, language policy, git hook behavior, migration review, and inbox handling.
- Project product decisions belong in \`wiki/decisions/\`, while these operating decisions stay in \`wiki/meta/\`.

Status: accepted
Scope: wiki operation
Canonical: [[meta/operating-model]], [[meta/decision-policy]]

| Date | Decision | Rationale | Rejected Alternative | Revisit Trigger | Canonical Link |
| --- | --- | --- | --- | --- | --- |
| ${today} | Keep the wiki root at \`./wiki\`. | Planning docs live with the project. | External docs only. | Another tool cannot read \`./wiki\` or the team needs another path. | [[meta/operating-model]] |
| ${today} | Split \`canonical/\` and \`decisions/\`. | Current truth and decision history are easier to scan when separated. | A single mixed docs directory. | The structure proves too heavy for small projects. | [[meta/decision-policy]] |
| ${today} | Inject only \`startup.md\` and \`index.md\` through Codex, Claude Code, and Cursor startup hooks, and route Gemini through compact context instructions; route detailed files Read On Demand. | Full canonical and decision bodies waste startup tokens. | Always read detailed canonical and decision files first. | Important context is repeatedly missed at startup. | [[startup]], [[index]] |
| ${today} | Use metadata headers on wiki knowledge pages. | Agents and humans can quickly judge status, scope, budget, and review triggers. | Body-only conventions. | Header maintenance costs more than it saves. | [[meta/operating-model]] |
| ${today} | Keep wiki operating docs in \`wiki/meta/\`. | Project truth stays focused on product/project content. | Store operating docs in \`canonical/\` or \`decisions/\`. | Meta docs become hard to discover. | [[meta/operating-model]] |
| ${today} | Bootstrap-generated operating documents are English by default. | Repository entry points and operating contracts are easier for public users to inspect. | Generate operating docs in a fixed non-English language. | The project intentionally targets a single-language local audience. | [[meta/operating-model]] |
| ${today} | Project canonical content language is chosen from user/project context. | User language and source material should drive project truth, not the bootstrap tool. | Hardcode Korean or English as the canonical content language. | A team requires a fixed language policy. | [[startup]], [[index]] |
| ${today} | Install git hook files but preserve existing \`core.hooksPath\` values and allow \`--no-git-config\`. | Public users may already have a hook chain such as Husky. | Always replace \`core.hooksPath\`. | Users prefer automatic setup and accept the side effect. | [[meta/operating-model]] |
| ${today} | Commit automation writes the \`Wiki-scope\` trailer. | Reviewers should see whether a commit touched startup, canonical docs, decisions, or wiki operations. | Leave wiki impact implicit in the diff. | Trailer format becomes too noisy. | [[meta/operating-model]] |
| ${today} | Migration may mark rows \`needs-human-review\`. | Ambiguous, risky, or high-impact legacy content should not be closed automatically. | Force every migrated row into adopted/rejected/resolved. | Human review queues become too large. | [[meta/operating-model]] |
| ${today} | Capture stores candidates in \`wiki/inbox/\`. | Useful ideas are not lost, but unreviewed content does not become canonical truth. | Save all conversation content directly into canonical docs. | Inbox content is frequently abandoned. | [[meta/operating-model]] |
`,
  "wiki/decisions/decision-pack-template.md": `${metadata("project-decision-template", "short", "wiki/meta/decision-policy.md", "decision pack format changes", "template")}
# <Topic> v<N> Decisions

Status: proposed | accepted | superseded
Scope:
Canonical:

| Date | Decision | Rationale | Rejected Alternative | Revisit Trigger | Canonical Link |
| --- | --- | --- | --- | --- | --- |
| YYYY-MM-DD |  |  |  |  |  |
`,
  "wiki/decisions/full-adr-template.md": `${metadata("project-decision-template", "short", "wiki/meta/decision-policy.md", "full ADR format changes", "template")}
# ADR: <Title>

Status: proposed | accepted | superseded
Date: YYYY-MM-DD
Canonical:

## Context

## Decision

## Consequences

## Rejected Alternatives

## Revisit Trigger
`,
  "wiki/sources/karpathy-llm-wiki.md": `${metadata("source-summary", "short", "wiki/meta/wiki-ops-v1-decisions.md", "source interpretation or reference link changes")}
# Karpathy LLM Wiki

## TL;DR

- This pattern favors continuously maintained markdown wiki context over repeatedly reconstructing context from scratch.
- This project applies the pattern to project-planning source-of-truth management.

Source: [karpathy/llm-wiki.md](https://gist.github.com/karpathy/442a6bf555914893e9891c11519de94f)
Checked: ${today}

## Applied Here

- \`wiki/startup.md\` stores compact session context.
- \`wiki/index.md\` routes reads and updates.
- \`wiki/canonical/\` stores current project truth.
- \`wiki/decisions/\` stores project decision history.
- \`wiki/meta/\` stores wiki operating rules and operating decisions.
`,
};
